name: new_alsb_env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch==2.4.1 --extra-index-url https://download.pytorch.org/whl/cu124
      - torchvision==0.19.1 --extra-index-url https://download.pytorch.org/whl/cu124