defaults:
  - /schema/job/active@_here_
  - __base__
  - dataset: waterbirds
  - model: resnet50
  - heuristic: random
  - _self_

reset_each_round: true
save_dict: false
n_al_steps: 10
n_initial: 590
query_size: 74
train_cfg:
  batch_size: 25
  checkpoint_freq: 10
  n_steps: 10
  rrr: true
  workers: 4
test_cfg:
  batch_size: ${train_cfg.batch_size}
  workers: ${train_cfg.workers}
resume: null
rrr: True
