defaults:
  - /schema/job/visual@_here_
  - dataset: waterbirds
  - override hydra/job_logging: default  
  - override hydra/hydra_logging: default  
  - _self_

hydra:
  job:
    chdir: True

seed: 42
wandb:
  mode: online
  project: smarter_xil
  entity: rigonmattia-university-of-trento
  tags: null

model: BiT-M-R50x1
batch_size: 5
