defaults:
  - /schema/job/visual@_here_
  - dataset: waterbirds
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

hydra:
  job:
    chdir: True

seed: 42
wandb:
  mode: disabled
  project: manhattan
  entity: yjng
model: BiT-M-R50x1
batch_size: 5
