defaults:
  - /schema/job/loss_landscape@_here_
  - __base__
  - dataset: waterbirds
  - model: resnet50
  - _self_

train_cfg:
  n_steps: 100
  batch_size: 8
  checkpoint_freq: 50
  workers: 4
test_cfg:
  batch_size: ${train_cfg.batch_size}
  workers: ${train_cfg.workers}

landscape_cfg:
  steps: 50
  deepcopy_model: true
num_samples_per_group: 500
